# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for theme
LUCI_PKGARCH:=all

PKG_NAME:=luci-theme-argon2
PKG_MAINTAINER:=anakdeso <@gmail.com>
PKG_VERSION:=2.5
PKG_RELEASE:=beta
PKG_LICENSE:=Apache-2.0
PKG_ARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
